### ISSUE TITLE
adduser のパスワードハッシュ生成をより安全にしたい

### ISSUE THREAD

**Issue by t-uda** [kusm/admin_tools#10]
https://github.com/kmc-jp/guildbook/issues/29 と同じアレです．コピペで終わるハズなのでやってください．

せっかくなので GitHub workflow の練習もしてください．つまり，この Issue にひもづけられた Pull Request という適切な形にして修正内容を送ってください．

**Comment by tennashi** [comment]
#11 これでいいのか??
